### ISSUE TITLE
Add Profile Stats by God

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#107]
When visiting a user's profile page, match history and a rank card are currently displayed. 
![image](https://github.com/user-attachments/assets/15df23df-cf4e-4d9d-bfd5-e698e2c78881)

We now have stats data available in the Mongo stats_civs collection. These are currently being used to power the statistics pages.

- Write a new backend endpoint in `/api` that will query mongo for stats for an individual profile.
  - Consider building it to accept filters by current patch, all time, etc.
- On the front end, create a new component to display a player's god stats, matchups, maps, etc. Use shadcn components whenever possible. Tables could work better than graphs here. https://ui.shadcn.com/

Example:
![image](https://github.com/user-attachments/assets/f23fb08e-7ff7-466e-9a5e-3c3439ef87e3)
https://aoe4world.com/players/707064

Definition of done:
- A user can visit their profile and view their stats for different major gods.

**Comment by cishiv** [comment]
I can take a stab at this one :)
