### ISSUE TITLE
Fix Reddit images that do not load

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#32]
Some of the Reddit previews do not load for various reason. One of them is Twitter previews, which requires the Twitter API to be implemented. Other suspects:

- images uploaded directly to reddit
- videos/gifs

**Comment by terrok9** [comment]
Can you show the expected behaviour?

You may just crop it from your stream.

You can create a free twitter API token that can just serve you well.
