### ISSUE TITLE
Add the ability to edit and deleted uploaded recorded games

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#88]
There is currently not ability to edit or delete a recorded game once it has been uploaded.

1. Build this as a forward feature, do not worry about this ability for past uploads
2. When games are uploaded, the rec is parsed and the metadata is saved to the recordedgames collection with an uploadedBy string. Update the mongo schema so also include and uploadedByUserId so that we can associated recs with the logged in user to allow for edit/delete.
3. Add the ability to edit a recorded game if it was uploaded by the logged in user. Right now, I think this would pretty much just be the rec title.
4. Add the ability to delete a recorded game if it was uploaded by the logged in user. I was a little hesitant to allow this feature as it could result in losing games, but think it is best for a user to be able to undo an upload (could have been the wrong game...etc)

5. BONUS - add a filter to allow uploaded by that includes options for:
- Anyone
- Me (as in the logged in user...not sure how show/hide this if the user is not logged in. Maybe could prompt for login if they aren't and select this)
- FitzBro

This last part could be up for discussion, and even be a separate issue potentially

**Comment by prateeksingh19** [comment]
I'm working on this

**Comment by erin-fitzpatric** [comment]
@prateeksingh19 is going to follow up with some minor fixes.. mostly revalidation related.
