### ISSUE TITLE
Fulfill Google AdSense Requirements to Reapply for Ads

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#89]
1. Verify that the sitemap is being generated correctly
2. Add an about us page
3. Add a privacy policy page and add Privacy Page to the footer. Include contact fitzbrogaming@gmail.com. 
4. Add a Contact Us page

See image for additional requirements from legibility checker:

https://www.getthit.com/tools/google-adsense-eligibility-checker
![image](https://github.com/user-attachments/assets/1406f139-23f2-42b3-9066-777a05a9a936)

**Comment by prateeksingh19** [comment]
I'm working on it

**Comment by prateeksingh19** [comment]
#98 will fix this

**Comment by ghost** [comment]
We are thrilled that our services are helping you enhance your product. Wishing you all the best!
