### ISSUE TITLE
Implement Shadcn Nav Menu

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#92]
Use the shadcn nav menu:
https://ui.shadcn.com/docs/components/navigation-menu

Replace the current navigation menu with this. 

Routes:
/recs
/stats/gods
/stats/matchups
/stats/maps
/resources

- Leave logo as is
- Recorded Games
- Statistics 
  - Gods
  - Matchups
  - Maps
- Resources

Condense socials in headers somehow.

**Comment by kinsyudev** [comment]
Working on this!

**Comment by erin-fitzpatric** [comment]
I'd like to keep socials in the header if possible, but they could go to the footer. Mostly want to keep the ko-fi link high profile for several donations.

Also consider the mobile nav. Open to this being improved...
