### ISSUE TITLE
Reafactor fetchRedditPosts to be an API Route aka Serverless Function w/Cache

### ISSUE THREAD

**Issue by erin-fitzpatric** [erin-fitzpatric/next-aom-stats#96]
Reddit posts are currently fetched directly from the server, rather than via a request to the API layer.
https://github.com/erin-fitzpatric/next-aom-gg/blob/main/src/server/fetchRedditPosts.ts

In next.js, all routes created in the `/api` become a severless function when deployed to vercel
https://vercel.com/docs/functions

1. Move this functionality to a new endpoint in `api/reddit/route.ts`
2. Refactor reddit-feed.tsx to make a get request to this new endpoint
3. Cache the response by adding headers like:
```js
    return new Response(JSON.stringify(civStatsAggregate), {
      headers: {
        "Content-Type": "application/json",
        "Cache-Control": "public, max-age=43200, stale-while-revalidate=43200",
      },
    });
```
I think the cache could be set to 1 hour, but this is open for discussion. Seems like a reasonable refresh rate and will help cut down on requests every someone hits the home page.

**Comment by JeanPec** [comment]
Hey I can work on this one

**Comment by JeanPec** [comment]
I added a last commit, I wanted to impelment a retry logic in the Get querry but I found it easier to just retry when fetching the call every 500ms

**Comment by judgemavi** [comment]
I have a PR up that changes reddit post to SSR instead of client browser via useEffect. there should be no need for cache as page's default caching strategy will apply
